### ISSUE TITLE
LO5 5.2 Use AI tools to assist in debugging code

### ISSUE THREAD

**Issue by JeremyGreig** [JeremyGreig/CI_Project_1_JG#11]
**User Story**

As a developer

I want to efficiently use AI tools to identify and resolve code issues

So that I can effectively test my code

**Acceptance Criteria:**

- [x] Code should pass Copilots checks
- [x] Reflection in the README.md identifying resolved bugs

**Tasks:** 

- [x] Create section in README.md
- [x] Ensure it's completed before project completion
