### ISSUE TITLE
LO4 4.41 Documentation

### ISSUE THREAD

**Issue by JeremyGreig** [JeremyGreig/CI_Project_1_JG#3]
**User Story**

As an: assessor

I want to: be able to read about the project in the README.md

So that: I can understand the maintainability 

**Acceptance Criteria:**

- [x] Explains the application's purpose
- [x] User value
- [x] Deployment procedure
- [x] Screenshots of the single-page application with brief descriptions and user value explanations
- [x] Attributes any code from external sources

**Tasks:** 

- [x] Create README
- [x] Detail user value
- [x] Detail deployment procedure
- [x] Add screenshots with descriptions of features demonstrating functionality and user benefits. 
- [x] Reference any external code
