### ISSUE TITLE
LO1 1.01 Front End Design

### ISSUE THREAD

**Issue by JeremyGreig** [JeremyGreig/CI_Project_1_JG#5]
**User Story**

As a mental health first aider
I want to access a cohesive one-page layout
So that I can support people who contact me

**Acceptance Criteria:**

- [ ] Website has one page
- [ ] There is a main navigation menu
- [ ] Content is structured
- [ ] Accessibility guidelines followed including colour contrast and alt-text
- [ ] No web content accessibility guideline (WCAG) errors
- [ ] Responsive design with no reduction in functionality

**Tasks:** 

- [ ] Create index.html
- [ ] Create style.css
- [ ] Pass final WCAG check
