### ISSUE TITLE
LO1 1.02 User Experience

### ISSUE THREAD

**Issue by JeremyGreig** [JeremyGreig/CI_Project_1_JG#6]
**User Story**

As a mental health first aider

I want information to be clear and accessible

So that I am able to access what I need

**Acceptance Criteria:**

- [x] Information organised using UX principles ensuring headers convey structure
- [x] User can initiate and control actions where required

**Tasks:** 

- [x] This should be completed by design, but can be corrected with further iterations if time is sensitive

**Comment by JeremyGreig** [comment]
This was completed to MVP, but bugs added to backlog covering semantic issue as well as problem with navigation bar
