### ISSUE TITLE
L02 2.2 Responsive Design

### ISSUE THREAD

**Issue by JeremyGreig** [JeremyGreig/CI_Project_1_JG#8]
**User Story**

As a user

I want the website to be responsive

So that I can access the information on any screen sizes

**Acceptance Criteria:**

- [x] Consistent layout across different screen sizes
- [x] CSS media queries
- [x] Clear and semantic HTML structure

**Tasks:** 

- [ ] Test the screen displays correctly on 3 device sizes and add screenshots to this ticket to confirm it passed the test

**Comment by JeremyGreig** [comment]
Issue with navigation bar:

![Image](https://github.com/user-attachments/assets/97947469-038d-4089-a7bc-c1d7bfd83a1d)

**Comment by JeremyGreig** [comment]
Correctly functioning laptop or larger screen

![Image](https://github.com/user-attachments/assets/06ba7c74-3b0d-41f9-a172-8f2cc6925297)
