### ISSUE TITLE
LO3 3.1 Cloud Deployment

### ISSUE THREAD

**Issue by JeremyGreig** [JeremyGreig/CI_Project_1_JG#9]
**User Story**

As a site owner

I want to access my website on a cloud platform

So that the website can be viewed by the users

**Acceptance Criteria:**

- [ ] Deploy final version to a cloud-based platform ensuring it matches the dev version
- [ ] Use Git and GitHub for version control
- [ ] Commented out code should be removed
- [ ] Links should all function correctly

**Tasks:** 

- [ ] Final version deployed 
- [ ] Clear version control
- [ ] Remove commented out code
- [ ] Check all links function
